---
abstract: 'Make payments using PayPal'
author:
  - 'Jan Henning Thorsen <jhthorsen@cpan.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-PayPal
no_index:
  directory:
    - t
    - inc
requires:
  IO::Socket::SSL: 1.84
  Mojolicious: 5.13
resources:
  bugtracker: https://github.com/jhthorsen/mojolicious-plugin-paypal/issues
  homepage: https://github.com/jhthorsen/mojolicious-plugin-paypal
  repository: https://github.com/jhthorsen/mojolicious-plugin-paypal.git
version: 0.05
